language: nix
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ https://datakurre.cachix.org/" | sudo
  tee -a /etc/nix/nix.conf
- echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  datakurre.cachix.org-1:ayZJTy5BDd8K4PW9uc9LHV+WCsdi/fu1ETIYZMooK78=" | sudo tee
  -a /etc/nix/nix.conf
script:
- nix-shell --run "make TEXFILE=how-plone-excels-in-gatsbyjs-content-mesh"
- nix-shell --run "make TEXFILE=zserver-reloaded-with-http2-and-websocket-support"
after_success:
- mkdir build TEXFILE=how-plone-excels-in-gatsbyjs-content-mesh
- mkdir build TEXFILE=zserver-reloaded-with-http2-and-websocket-support
- mkdir -p build/zserver
- mv *.pdf build
- echo '<meta http-equiv="refresh" content= "0;url=how-plone-excels-in-gatsbyjs-content-mesh.pdf"
  />' > build/index.html
- echo '<meta http-equiv="refresh" content= "0;url=../zserver-reloaded-with-http2-and-websocket-support.pdf"
  />' > build/zserver/index.html
- touch build/.nojekyll
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  local-dir: "./build"
  target-branch: gh-pages
  keep-history: false
  skip-cleanup: true
  on:
    branch: master
env:
  global:
    secure: TADJ1pBXvR/R+nRwtRpLet4JKVCieXiAOtDqOyzZkLFbTaPuECw3wEPun4HJGjuvjw5/2+0qbIloUNx/21xo2REOBLX+4nyuxEBF8cczfl21zXCN5muff0hX1Cpmde4hU+B5PtnYl9zRi6JROAVljFm22si8cO/dmxomc+strPZYkZeZfIgzW5TIY1mwzGj06qR44aSvlk9Lsyb+dEWkpo2v3qjkXkbiAAbpmjP/Euo6kZ3kYWD2ySi8VkDAaNUABD0yVoDhpKbx34boQpKuaBvEvzJkHK0DDuRNim4GbjLIourROKfnxggOH99mk/0wCffAt43yzUc25ome2ra5ka50sXAsONJDiMSIgvuWe79/S44gPe9ZgEdz+fzzMtaWUj6qasZLycqutSdYQlhiao6C/wJgX+33Xe7dN8KOdGsYVCwZp9jBCJRvDQRMwRc/FFr8PegD9UayB8TkR1Pav/wSUFwTsHiNaGsL614K4m0hWDpYR3OU+WsD8sq5KrObHGv6hBE7dca4NcClo/iyTC5MZ3H+8Q0NQdgwT9iA+6k3qNOdFcEE7P2dJoSKa0C5ppe2TtWsdIX1YMu1MAprMBU0FU93Pp6D3TZAjY07obu3nRUiOKSev0PlIgQs85umiDPM9HQNyhrqK1dk3ULed7Ed2pGML5atBoRVNTPSFik=
